### ISSUE TITLE
Create setup script

### ISSUE THREAD

**Issue by Ryo8-k2arl** [Ryo8-k2arl/MyCommands#1]
# Create Setup Script

## Abst.

DebianベースのLinuxインストール時のセットアップ用スクリプトを作成する

## Task

- [ ] update
- [ ] clean
- [ ] self setup
- [ ] install appliction (chrome, VS Code...)
- [ ] japanase localization
- [ ] delete application (thunderbird, firefox)
- [ ] build enviroment developing

**Comment by Ryo8-k2arl** [comment]
## additional task

- [ ] Refactor code
- [ ] .vimrc の自動生成
- [ ] 引数なし時のエラー出力（現在はall実行だが、間違い発生多数の恐れあり）
